# Generated by Django 4.1.3 on 2023-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_encrypt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='audiomodel',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiomodel2',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
