# Generated by Django 4.0 on 2022-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(default='hello', max_length=2000),
        ),
    ]
