# Generated by Django 4.0 on 2022-04-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_image_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
