# Generated by Django 4.0 on 2022-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0003_rename_image_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
