# Generated by Django 4.0 on 2022-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0004_imagemodel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
