# Generated by Django 4.1.3 on 2023-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0005_alter_imagemodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel2',
            name='key',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
