# Generated by Django 4.1.3 on 2023-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0006_remove_imagemodel_title_imagemodel_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='key',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imagemodel2',
            name='key',
            field=models.IntegerField(),
        ),
    ]
